# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'service-catalog-front'
  imageTag: 'v1.0.$(build.buildId)'

stages:
  - stage: build
    displayName: Build
    jobs:
      - job:
        steps:
          - task: Npm@1
            displayName: Install dependecies
            inputs:
              command: install
          - task: Npm@1
            displayName: Transpile Code
            inputs:
              command: custom
              customCommand: run build
              verbose: true
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'build'
              artifactType: 'pipeline'
  - stage: security
    dependsOn: build
    displayName: Snyk Security Scan
    jobs:
      - job:
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              source: 'current'
              artifact: 'build'
              path: '$(Build.SourcesDirectory)'
          - task: SnykSecurityScan@1
            inputs:
              serviceConnectionEndpoint: 'Snyk'
              testType: 'app'
              monitorWhen: 'always'
              failOnIssues: false
              projectName: 'front'
              organization: 'c60c0b73-b647-496b-874f-f4487ef9d092'
  - stage: docker
    dependsOn: security
    displayName: Build Docker Images
    jobs:
      - job:
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              source: 'current'
              artifact: 'builf'
              path: '$(Build.SourcesDirectory)'
          - task: Docker@2
            displayName: Docker Build
            inputs:
              command: build
              repository: $(imageName)
              arguments: --no-cache
              tags: |
                $(imageTag)
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                  docker image save -o $(Build.SourcesDirectory)/image.tar $(imageName):$(imageTag)
          - task: CopyFiles@2
            displayName: 'Copy Files images'
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)'
              Contents: 'image.tar'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
              CleanTargetFolder: true
              preserveTimestamp: true
          - task: CopyFiles@2
            displayName: 'Copy Files kubernetes definition'
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)/k8s'
              Contents: '*'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
              CleanTargetFolder: true
              preserveTimestamp: true
          - bash: 'cd $(Build.ArtifactStagingDirectory) && ls -la'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'image'
              artifactType: 'pipeline'
  - stage:
    dependsOn: docker
    displayName: Publish Artifact
    jobs:
      - job:
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              source: 'current'
              artifact: 'image'
              path: '$(Build.ArtifactStagingDirectory)'
          - bash: 'cd $(Build.ArtifactStagingDirectory) && ls -la'
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'service-catalog'
