# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

pool:
  vmImage: ubuntu-latest

variables:
  group: FRONT-SERVICE-CATALOG
  imageName: 'service-catalog-front'
  imageTag: 'v1.0.$(build.buildId)'

stages:
  - stage: build
    displayName: Build
    jobs:
      - job:
        steps:
          - task: Npm@1
            displayName: Install dependecies
            inputs:
              command: install
          - task: Npm@1
            displayName: Transpile Code
            inputs:
              command: custom
              customCommand: run build
              verbose: true
          - bash: 'cd $(Build.SourcesDirectory) && ls -la'
          - script: |
              sed -i "s/latest/$(imageTag)/" ./k8s/definition.yaml
          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: '$(Build.SourcesDirectory)'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.SourcesDirectory)/build.zip'
              replaceExistingArchive: true
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.SourcesDirectory)/build.zip'
              artifactName: 'build'
  - stage: security
    dependsOn: build
    displayName: Snyk Security Scan
    jobs:
      - job:
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              source: 'current'
              artifact: 'build'
              path: '$(Build.SourcesDirectory)'
          - bash: 'cd $(Build.SourcesDirectory) && ls -la'
          - task: ExtractFiles@1
            inputs:
              archiveFilePatterns: '**/*.zip'
              destinationFolder: '$(Build.SourcesDirectory)'
              cleanDestinationFolder: false
              overwriteExistingFiles: true
          - bash: 'cd $(Build.SourcesDirectory) && ls -la'
          - task: SnykSecurityScan@1
            inputs:
              serviceConnectionEndpoint: 'Snyk'
              testType: 'app'
              monitorWhen: 'always'
              failOnIssues: false
              projectName: 'front'
              organization: 'c60c0b73-b647-496b-874f-f4487ef9d092'
  - stage: docker
    displayName: Build Docker Images
    jobs:
      - job:
        steps:
          - task: Docker@2
            displayName: Docker Build
            inputs:
              command: build
              repository: $(imageName)
              arguments: --build-arg CLIENT_ID=$(CLIENT_ID) --build-arg TENANT_ID=$(TENANT_ID) --build-arg REDIRECT_URI=$(REDIRECT_URI) --no-cache
              tags: |
                $(imageTag)
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                  docker image save -o $(Build.SourcesDirectory)/image.tar $(imageName):$(imageTag)
          - task: CopyFiles@2
            displayName: 'Copy Files images'
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)'
              Contents: 'image.tar'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
              CleanTargetFolder: true
              preserveTimestamp: true
          - task: CopyFiles@2
            displayName: 'Copy Files kubernetes definition'
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)/k8s'
              Contents: '*'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
              CleanTargetFolder: false
              preserveTimestamp: true
          - script: |
              echo $(imageTag) > $(Build.ArtifactStagingDirectory)/tag.txt
            displayName: 'Save tag to get in release pipeline'
          - bash: 'cd $(Build.ArtifactStagingDirectory) && ls -la'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'image'
  - stage:
    dependsOn: ['docker', 'security']
    displayName: Publish Artifact
    jobs:
      - job:
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              source: 'current'
              artifact: 'image'
              path: '$(Build.ArtifactStagingDirectory)'
          - bash: 'cd $(Build.ArtifactStagingDirectory) && ls -la'
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'service-catalog'
