apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-catalog-front
  namespace: service-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      component: service-catalog-front
  template:
    metadata:
      labels:
        component: service-catalog-front
    spec:
      containers:
        - name: service-catalog-front
          image: tecnoandina01.azurecr.io/service-catalog-front:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: cluster-secrets
                  key: SSO_CLIENT_ID
            - name: TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: cluster-secrets
                  key: SSO_TENANT_ID
            - name: REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: cluster-secrets
                  key: SSO_REDIRECT_URI
      imagePullSecrets:
        - name: tecnoregistry
---
apiVersion: v1
kind: Service
metadata:
  name: service-catalog
  namespace: service-catalog
spec:
  selector:
    component: service-catalog-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
# Ingress service configuration
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: service-catalog
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
spec:
  ingressClassName: ingress-nginx
  rules:
    - host: service-catalog-dev.tecnoandina.cl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-catalog
                port:
                  number: 80
