apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-catalog-front
spec:
  replicas: 1
  selector:
    matchLabels:
      ip-service: service-catalog-front
  template:
    metadata:
      labels:
        ip-service: service-catalog-front
    spec:
      containers:
        - name: service-catalog-front
          image: tecnoandina01.azurecr.io/service-catalog-front:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
